
config:
  n8n:
    host: ${n8n_hostname}
    protocol: https
    port: 5678


secretRefs:
  existingSecret: n8n-secrets


queueMode:
  enabled: true
  workerReplicaCount: 2
  workerConcurrency: 10


database:
  type: postgresdb
  useExternal: true

  host: postgresql.n8n.svc.cluster.local
  port: 5432

  database: n8n
  schema: public
  user: n8n

  passwordSecret:
    name: n8n-db-password
    key: password


redis:
  enabled: true
  useExternal: true

  host: redis-master.n8n.svc.cluster.local
  port: 6379

  passwordSecret:
    name: n8n-redis-password
    key: password


webhook:
  enabled: true
  url: https://${n8n_hostname}


ingress:
  enabled: true

  className: kong

  hosts:
    - host: ${n8n_hostname}
      paths:
        - path: /
          pathType: Prefix

  tls:
    - secretName: n8n-tls
      hosts:
        - ${n8n_hostname}

pdb:
  enabled: true
  minAvailable: 1

securityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

  
